### ISSUE TITLE
Cannot use 'Object' as class name as it is reserved on PHP 7.2.7

### ISSUE THREAD

**Issue by ThatGuySam** [incraigulous/rest-repositories#3]
Getting an error about using Object as a Class name

Library Version 2.1
PHP 7.2.7

<img width="1792" alt="screenshot 2018-07-19 17 08 29" src="https://user-images.githubusercontent.com/2830379/42972875-9dfa03be-8b76-11e8-900d-f4a3bfa93feb.png">

**Comment by incraigulous** [comment]
Object has been renamed to `\Incraigulous\RestRepositories\Item` in https://github.com/incraigulous/rest-repositories/releases/tag/2.2.0.

**Comment by ThatGuySam** [comment]
🔥🔥🔥
